//
//  NSString+Additions.m
//  TBBusiness
//
//  Created by 韩琼 on 14-5-7.
//  Copyright (c) 2014年 Taobao. All rights reserved.
//

#import <CommonCrypto/CommonHMAC.h>
#import <CommonCrypto/CommonDigest.h>

#import "NSData+Additions.h"
#import "NSDate+Additions.h"
#import "UIColor+Additions.h"
#import "NSString+Additions.h"

#define HANZI_START 19968
#define HANZI_COUNT 20902

static char FirstLetterArray[HANZI_COUNT] =
"YDKQSXNWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYQZJJFGCCLZZNWDWZJLJPFYYNNJJTMYNZWZHFLZPPQHGCCYYNMJQYXXGD"
"NNSNSJNJNSNNMLNRXYFSNGNNNNQZGGLLYJLNYZSSECYKYYHQWJSSGGYXYQYJTWKTJHYCHMNXJTLHJYQBYXDLDWRRJNWYSRLDZJPC"
"BZJJBRCFSLNCZSTZFXXCHTRQGGDDLYCCSSYMMRJCYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXJBCFTZYHHYCYSWCCYXSCLCXXWZ"
"CXNBGNNXBXLZSQSBSJPYSAZDHMDZBQBSCWDZZYYTZHBTSYYFZGNTNXJYWQNKNPHHLXGYBFMJNBJHHGQTJCYSXSTKZGLYCKGLYSMZ"
"XYALMELDCCXGZYRJXJZLNJZCQKCNNJWHJCZCCQLJSTSTBNHBTYXCEQXKKWJYFLZQLYHJXSPSFXLMPBYSXXXYTCCNYLLLSJXFHJXP"
"JBTFFYABYXBCCZBZYCLWLCZGGBTSSMDTJCXPTHYQTGJJXCJFZKJZJQNLZWLSLHDZBWJNCJZYZSQNYCQYNZCJJWYBRTWPYFTWEXCS"
"KDZCTBYHYZQYYJXZCFBZZMJYXXSDCZOTTBZLJWFCKSCSXFYRLRYGMBDTHJXSQJCCSBXYYTSWFBJDZTNBCNZLCYZZPSACYZZSQQCS"
"HZQYDXLBPJLLMQXQYDZXSQJTZPXLCGLQDCWZFHCTDJJSFXJEJJTLBGXSXJMYJJQPFZASYJNSYDJXKJCDJSZNBARTCCLNJQMWNQNC"
"LLLKBDBZZSYHQCLTWLCCRSHLLZNTYLNEWYZYXCZXXGDKDMTCEDEJTSYYSSDQDFMXDBJLKRWNQLYBGLXNLGTGXBQJDZNYJSJYJCJM"
"RNYMGRCJCZGJMZMGXMMRYXKJNYMSGMZZYMKNFXMBDTGFBHCJHKYLPFMDXLXJJSMSQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCN"
"FNNFFPFKHKGDPQXKTACJDHHZDDDRRCFQYJKQCCWJDXHWJLYLLZGCFCQJSMLZPBJJBLSBCJGGDCKKDEZSQCCKJGCGKDJTJLLZYCXK"
"LQCCGJCLTFPCQCZGWBJDQYZJJBYJHSJDDWGFSJGZKCJCTLLFSPKJGQJHZZLJPLGJGJJTHJJYJZCCMLZLYQBGJWMLJKXZDZNJQSYZ"
"MLJLLJKYWXMKJLHSKJHBMCLYYMKXJQLBMLLKMDXXKWYXWSLMLPSJQQJQXYQFJTJDXMXXLLCRQBSYJBGWYNNGGBCNXPJTGPAPFGDJ"
"QBHBNCFJYZJKJKHXQFGQCKFHYGKHDKLLSDJQXPQYAYBNQSXQNSZSWHBSXWHXWBZZXDMNDJBSBKBBZKLYLXGWXJJWAQZMYWSJQLSJ"
"XXJQWJEQXNCHETLZALYYYSZZPNKYZCPTLSHTZCFYCYXYLJSDCJQAGYSLCLLYYYSSLQQQNLDXZSCCSCADYCJYSFSGBFRSSZQSBXJP"
"SJYSDRCKGJLGTKZJZBDKTCSYQPYHSTCLDJNHMYMCGXYZHJDCTMHLTXZHYLAMOXYJCLTYFBQQJPFBDFEHTHSQHZYWWCNCXCDWHOWG"
"YJLEGMDQCWGFJHCSNTMYDOLBYGNQWESQPWNMLRYDZSZZLYQPZGCWXHNXPYXSHMDQJGZTDPPBFBHZHHJYFDZWKGKZBLDNZSXHQEEG"
"ZXYLZMMZYJZGSZXKHKHTXEXXGYLYAPSTHXDWHZYDPXAGKYDXBHNHNKDNJNMYHYLPMGECSLNZHKXXLBZZLBMLSFBHHGSGYYGGBHSC"
"YAJTXGLXTZMCWZYDQDQMNGDNLLSZHNGJZWFYHQSWSCELQAJYNYTLSXTHAZNKZZSDHLAXXTWWCJHQQTDDWZBCCHYQZFLXPSLZQGPZ"
"SZNGLYDQTBDLXNTCTAJDKYWNSYZLJHHDZCKRYYZYWMHYCHHHXHJKZWSXHDNXLYSCQYDPSLYZWMYPNKXYJLKCHTYHAXQSYSHXASMC"
"HKDSCRSGJPWQSGZJLWWSCHSJHSQNHNSNGNDANTBAALCZMSSTDQJCJKTSCJNXPLGGXHHGOXZCXPDMMHLDGTYBYNJMXHMRZPLXJZCK"
"ZXSHFLQXXCDHXWZPCKCZCDYTCJYXQHLXDHYPJQXNLSYYDZOZJNHHQEZYSJYAYXKYPDGXDDNSPPYZNDHTHRHXYDPCJJHTCNNCTLHB"
"YNYHMHZLLNNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZNXCLCCLYLNZSXNJZZLNNNNWHYQSNJHXYNTTDKYJPYCHHYEGKCWTWLGJRLGG"
"TGTYGYHPYHYLQYQGCWYQKPYYETTTTLHYYLLTYTTSYLNYZWGYWGPYDQQZZDQNNKCQNMJJZZBXTQFJKDFFBTKHZKBXDJJKDJJTLBWF"
"ZPPTKQTZTGPDWNTPJYFALQMKGXBCCLZFHZCLLLLANPNXTJKLCCLGYHDZFGYDDGCYYFGYDXKSSENDHYKDNDKNNAXXHBPBYYHXCCGA"
"PFQYJJDMLXCSJZLLPCNBSXGJYNDYBWJSPCWJLZKZDDTACSBKZDYZYPJZQSJNKKTKNJDJGYEPGTLNYQNACDNTCYHBLGDZHBBYDMJR"
"EGKZYHEYYBJMCDTAFZJZHGCJNLGHLDWXJJKYTCYKSSSMTWCTTQZLPBSZDTWCXGZAGYKTYWXLNLCPBCLLOQMMZSSLCMBJCSDZKYDC"
"ZJGQJDSMCYTZQQLNZQZXSSBPKDFQMDDZZSDDTDMFHTDYCNAQJQKYPBDJYYXTLJHDRQXLMHKYDHRNLKLYTWHLLRLLRCXYLBNSRNZZ"
"SYMQZZHHKYHXKSMZSYZGCXFBNBSQLFZXXNNXKXWYMSDDYQNGGQMMYHCDZTTFGYYHGSBTTYBYKJDNKYJBELHDYPJQNFXFDNKZHQKS"
"BYJTZBXHFDSBDASWPAWAJLDYJSFHBLCNNDNQJTJNCHXFJSRFWHZFMDRFJYXWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZ"
"EMMQBSQEHXFZNBMFLZZSRSYQJGSXWZJSPRYTJSJGSKJJGLJJYNZJJXHGJKYMLPYYYCXYCGQZSWHWLYRJLPXSLCXMNSMWKLCDNKNY"
"NPSJSZHDZEPTXMWYWXYYSYWLXJQCQXZDCLAEELMCPJPCLWBXSQHFWRTFNJTNQJHJQDXHWLBYCCFJLYLKYYNLDXNHYCSTYYWNCJTX"
"YWTRMDRQNWQCMFJDXZMHMAYXNWMYZQTXTLMRSPWWJHANBXTGZYPXYYRRCLMPAMGKQJSZYCYMYJSNXTPLNBAPPYPYLXMYZKYNLDGY"
"JZCCHNLMZHHANQNBGWQTZMXXMLLHGDZXNHXHRXYCJMFFXYWCFSBSSQLHNNDYCANNMTCJCYPNXNYTYCNNYMNMSXNDLYLYSLJNLXYS"
"SQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXNCHLSNMCJSCYZNFZLXBRNNNYLMNRTGZQYSATSWRYHYJZMGDHZGZDWYBSSCSKXSYHYTSXG"
"CQGXZZBHYXJSCRHMKKBSCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCJGQHWLSNZSWXKHLJHYYBQCBFCDSXDLDSPFZFSKJJZWZXSDDX"
"JSEEEGJSCSSYGCLXXNWWYLLYMWWWGYDKZJGGGGGGSYCKNJWNJPCXBJJTQTJWDSSPJXCXNZXNMELPTFSXTLLXCLJXJJLJSXCTNSWX"
"LENNLYQRWHSYCSQNYBYAYWJEJQFWQCQQCJQGXALDBZZYJGKGXBLTQYFXJLTPYDKYQHPMATLCNDNKXMTXYNHKLEFXDLLEGQTYMSAW"
"HZMLJTKYNXLYJZLJEEYYBQQFFNLYXHDSCTGJHXYWLKLLXQKCCTNHJLQMKKZGCYYGLLLJDCGYDHZWYPYSJBZJDZGYZZHYWYFQDTYZ"
"SZYEZKLYMGJJHTSMQWYZLJYYWZCSRKQYQLTDXWCDRJALWSQZWBDCQYNCJNNSZJLNCDCDTLZZZACQQZZDDXYBLXCBQJYLZLLLJDDZ"
"JGYQYJZYXNYYYEXJXKSDAZNYRDLZYYYNJLSLLDYXJCYKYWNQCCLDDNYYYNYCGCZHJXCCLGZQJGNWNNCQQJYSBZZXYJXJNXJFZBSB"
"DSFNSFPZXHDWZTDMPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPNGPHDMJTHZSMMBGZMBZJCFZHFCBBNMQ"
"DFMBCMCJXLGPNJBBXGYHYYJGPTZGZMQBQDCGYBJXLWNKYDPDYMGCFTPFXYZTZXDZXTGKPTYBBCLBJASKYTSSQYYMSCXFJHHLSLLS"
"JPQJJQAKLYLDLYCCTSXMCWFGNGBQXLLLLNYXTYLTYXYTDPJHNHGNKBYQNFJYYZBYYESSESSGDYHFHWTCQBSDZJTFDMXHCNJZYMQW"
"SRXJDZJQBDQBBSDJGNFBKNBXDKQHMKWJJJGDLLTHZHHYYYYHHSXZTYYYCCBDBPYPZYCCZTJPZYWCBDLFWZCWJDXXHYHLHWCZXJTC"
"NLCDPXNQCZCZLYXJJCJBHFXWPYWXZPCDZZBDCCJWJHMLXBQXXBYLRDDGJRRCTTTGQDCZWMXFYTMMZCWJWXYYWZZKYBZCCCTTQNHX"
"NWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBTHHJDLSZDDYTYFJPXYNGFXBYQXZBHXCPXXTNZDNNYCNXSXLHKMZXLTHDHKGHXXSSHQYHH"
"CJYXGLHZXCXNHEKDTGQXQYPKDHENTYKCNYMYYJMKQYYYJXZLTHHQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKT"
"LXKKNQCDGCJWYJJLYHHQYTTNWCHHXCXWHERZJYDJCCDBQCDGDNYXZDHCQRXCBHZTQCBXWGQWYYBXHMBYMYKDYECMQKYAQYNGYZSL"
"FNKKQGYSSQYSHNGJCTXKZYCSSBKYXHYYLSTYCXQTHYSMNSCPMMGCCCCCMNZTASMGQZJHKLOSJYLSWTMQZYQKDZLJQQYPLZYCZTCQ"
"QPBBCJZCLPKHQCYYXXDTDDDSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWHDQQQCKXYAMYLSJHMLALYGXCYYDMAMDQMLMCZNNYYBZ"
"XKYFLMCNCMLHXRCJJHSYLNMTJGGZGYWJXSRXCWJGJQHQZDQJDCJJSKJKGDZCGJJYJYLXZXXCDQHHHESLMHLFSBDJSYYSHFYSSCZQ"
"LPBDRFNZTZDKYKHSCCGKWTQZCKMSYNBCRXQBJYFAXPZZEDZCJYKBCJWHYJBQZZYWNYSZPTDKZPFPBAZTKLQNHBBZPTPPTYZZYBHN"
"YDCPZMMCYCQMCJFZZDCMNLFPBPLNGQJTBTTAJZPZBBDNJKLJQYLNBZQHKSJZNGGQSTZKCXCHPZSNBCGZKDDZQANZGJKDRTLZLDWJ"
"NJZLYWTXNDJZJHXNATNCBGTZCSSKMLJPJYTSNWXCFJWJJTKHTZPLBHSNJSSYJBHBJYZLSTLSBJHDNWQPSLMMFBJDWAJYZCCJTBNN"
"NZWXXCDSLQGDSDPDZGJTQQPSQLYYJZLGYHSDLCTCBJTKTYCZJTQKBSJLGNNZDNCSGPYNJZJJYYKNHRPWSZXMTNCSZZYSHBYHYZAX"
"YWKCJTLLCKJJTJHGCSSXYQYCZBYNNLWQCGLZGJGQYQCCZSSBCRBCSKYDZNXJSQGXSSJMECNSTJTPBDLTHZWXQWQCZEXNQCZGWESG"
"SSBYBSTSCSLCCGBFSDQNZLCCGLLLZGHZCTHCNMJGYZAZCMSKSSTZMMZCKBJYGQLJYJPPLDXRKZYXCCSNHSHHDZNLZHZJJCDDCBCJ"
"XLBFQBCZZTPQDNNXLJCTHQZJGYLKLSZZPCJDSCQJHJQKDXGPBAJYNNSMJTZDXLCJYRYYNHJBNGZJKMJXLTBSLLRZPYLSSZNXJHLL"
"HYLLQQZQLSYMRCNCXSLJMLZLTZLDWDJJLLNZGGQXPPSKYGGGGBFZBDKMWGGCXMCGDXJMCJSDYCABXJDLNBCDDYGSKYDQDXDJJYXH"
"SAQAZDZFSLQXXJNQZYLBLXXWXQQZBJZLFBBLYLWDSLJHXJYZJWTDJCYFQZQZZDZSXZZQLZCDZFXHWSPYNPQZMLPPLFFXJJNZZYLS"
"JNYQZFPFZGSYWJJJHRDJZZXTXXGLGHTDXCSKYSWMMTCWYBAZBJKSHFHGCXMHFQHYXXYZFTSJYZBXYXPZLCHMZMBXHZZSSYFDMNCW"
"DABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSYXQQJGZYZAWLLCWXZNXGYXYHFMKHYDWSQMNJNAYCYS"
"PMJKGWCQHYLAJGMZXHMMCNZHBHXCLXDJPLTXYJKDYYLTTXFQZHYXXSJBJNAYRSMXYPLCKDNYHLXRLNLLSTYCYYQYGZHHSCCSMCCT"
"ZCXHYQFPYYRPBFLFQNNTSZLLJMHWTCJQYZWTLNMLMDWMBZZSNZRBPDDDLQJJBXTCSNZQQYGWCSXFWZLXCCRSZDZMCYGGDYQSGTNN"
"NLSMYMMSYHFBJDGYXCCPSHXCZCSBSJYYGJMPBWAFFYFNXHYDXZYLREMZGZZYNDSZNLLJCSQFNXXKPTXZGXJJGBMYYSSNBTYLBNLH"
"BFZDCYFBMGQRRMZSZXYSJTZNNYDZZCDGNJAFJBDKNZBLCZSZPSGCYCJSZLMNRZNBZZLDLNLLYSXSQZQLCXZLSGKBRXBRBZCYCXZJ"
"ZEEYFGKLZLNYHGZCGZLFJHGTGWKRAAJYZKZQTSSHJJXDZYZNYNNZYRZDQQHGJZXSSZBTKJBBFRTJXLLFQWJGCLQTYMBLPZDXTZAG"
"BDHZZRBGJHWNJTJXLKSCFSMWLLDCYSJTXKZSCFWJLBNNTZLLJZLLQBLCQMQQCGCDFPBPHZCZJLPYYGHDTGWDXFCZQYYYQYSRCLQZ"
"FKLZZZGFFCQNWGLHJYCJJCZLQZZYJBJZZBPDCSNNJGXDQNKNLZNNNNPSNTSDYFWWDJZJYSXYYCZCYHZWBBYHXRYLYBHKJKSFXTJJ"
"MMCHHLLTNYYMSXXYZPDJJYCSYCWMDJJKQYRHLLNGPNGTLYYCLJNNNXJYZFNMLRGJJTYZBSYZMSJYJHGFZQMSYXRSZCYTLRTQZSST"
"KXGQKGSPTGXDNJSGCQCQHMXGGZTQYDJJZNLBZNXQLHYQGGGTHQSCBYHJHHKYYGKGGCMJDZLLCCLXQSFTGJSLLLMLCSKCTBLJSZSZ"
"MMNYTPZSXQHJCNNQNYEXZQZCPSHKZZYZXXDFGMWQRLLQXRFZTLYSTCTMJCSJJTHJNXTNRZTZFQRHCGLLGCNNNNJDNLNNYTSJTLNY"
"XSSZXCGJZYQPYLFHDJSBBDCZGJJJQZJQDYBSSLLCMYTTMQNBHJQMNYGJYEQYQMZGCJKPDCNMYZGQLLSLNCLMHOLZGDYLFZSLNCNZ"
"LYLZCJESHNYLLNXNJXLYJYYYXNBCLJSSWCQQNNYLLZLDJNLLZLLBNYLNQCHXYYQOXCCQKYJXXXYKLKSXEYQHCQKKKKCSNYXXYQXY"
"GWTJOHTHXPXXHSNLCYKYCHZZCBWQBBWJQCSCSZSSLCYLGDDSJZMMYMCYTSDSXXSCJPQQSQYLYFZYCHDJYNYWCBTJSYDCHCYDDJLB"
"DJJSODZYQYSKKYXDHHGQJYOHDYXWGMMMAZDYBBBPPBCMNNPNJZSMTXERXJMHQDNTPJDCBSNMSSYTHJTSLMLTRCPLZSZMLQDSDMJM"
"QPNQDXCFRNNFSDQQYXHYAYKQYDDLQYYYSSZBYDSLNTFGTZQBZMCHDHCZCWFDXTMQQSPHQWWXSRGJCWNNTZCQMGWQJRJHTQJBBGWZ"
"FXJHNQFXXQYWYYHYSCDYDHHQMRMTMWCTBSZPPZZGLMZFOLLCFWHMMSJZTTDHLMYFFYTZZGZYSKJJXQYJZQBHMBZCLYGHGFMSHPCF"
"ZSNCLPBQSNJYZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLNADYMLYMQJPWXXHXSKTQJEZRPXXZGHMHWQPW"
"QLYJJQJJZSZCNHJLCHHNXJLQWZJHBMZYXBDHHYPYLHLHLGFWLCFYYTLHJJCWMSCPXSTKPNHJXSNTYXXTESTJCTLSSLSTDLLLWWYH"
"DNRJZSFGXSSYCZYKWHTDHWJGLHTZDQDJZXXQGGHLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYNSPCHYLHQYQTMZYMBYWRFQYK"
"JSYSLZDNJMPXYYSSRHZJNYQTQDFZBWWDWWRXCWGGYHXMKMYYYHMXMZHNKSEPMLQQMTCWCTMXMXJPJJHFXYYZSJZHTYBMSTSYJZNQ"
"JNYTLHYNBYQCLCYCNZWSMYLKNJXLGGNNPJGTYSYLYMZSKTTWLGSMZSYLMPWLCWXWQCSSYZSYXYRHSSNTSRWPCCPWCMHDHHXZDZYF"
"JHGZTTSBJHGYGLZYSMYCLLLXBTYXHBBZJKSSDMALHHYCFYGMQYPJYJQXJLLLJGCLZGQLYCJCCTOTYXMTMSHLLWLQFXYMZMKLPSZZ"
"CXHKJYCLCTYJCYHXSGYXNNXLZWPYJPXHJWPJPWXQQXLXSDHMRSLZZYDWDTCXKNSTZSHBSCCSTPLWSSCJCHJLCGCHSSPHYLHFHHXJ"
"SXALLNYLMZDHZXYLSXLMZYKCLDYAHLCMDDYSPJTQJZLNGJFSJSHCTSDSZLBLMSSMNYYMJQBJHRZWTYYDCHJLJAPZWBGQXBKFNBJD"
"LLLLYYLSJYDWHXPSBCMLJPSCGBHXLQHYRLJXYSWXHHZLLDFHLNNYMJLJYFLYJYCDRJLFSYZFSLLCQYQFGQYHNSZLYLMDTDJCNHBZ"
"LLNWLQXYGYYHBMGDHXXNHLZZJZXCZZZCYQZFNGWPYLCPKPYKPMCLGKDGXZGXWQBDXZZKZFBDDLZXJTPJPTTBYTHZZDWSLCPNHSLT"
"JXXQLHYXXXYWZYSWTTZKHLXZXZPYHGZHKNFSYHNTJRNXFJCPJZTWHPLSHFCRHNSLXXJXXYHZQDXQWNNHYHMJDBFLKHCXCWHJFYJC"
"FPQCXQXZYYYJYGRPYNSCSNNNNCHKZDYHFLXXHJJBYZWTTXNNCYJJYMSWYXQRMHXZWFQSYLZNGGBHYXNNBWTTCSYBHXXWXYHHXYXN"
"KNYXMLYWRNNQLXBBCLJSYLFSYTJZYHYZAWLHORJMNSCZJXXXYXCHCYQRYXQZDDSJFSLYLTSFFYXLMTYJMNNYYYXLTZCSXQCLHZXL"
"WYXZHNNLRXKXJCDYHLBRLMBRDLAXKSNLLJLYXXLYNRYLCJTGNCMTLZLLCYZLPZPZYAWNJJFYBDYYZSEPCKZZQDQPBPSJPDYTTBDB"
"BBYNDYCNCPJMTMLRMFMMRWYFBSJGYGSMDQQQZTXMKQWGXLLPJGZBQRDJJJFPKJKCXBLJMSWLDTSJXLDLPPBXCWKCQQBFQBCCAJZG"
"MYKBHYHHZYKNDQZYBPJNSPXTHLFPNSYGYJDBGXNHHJHZJHSTRSTLDXSKZYSYBMXJLXYSLBZYSLZXJHFYBQNBYLLJQKYGZMCYZZYM"
"CCSLNLHZHWFWYXZMWYXTYNXJHBYYMCYSBMHYSMYDYSHNYZCHMJJMZCAAHCBJBBHBLYTYLSXSNXGJDHKXXTXXNBHNMLNGSLTXMRHN"
"LXQQXMZLLYSWQGDLBJHDCGJYQYYMHWFMJYBBBYJYJWJMDPWHXQLDYAPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQKX"
"BEXYXHGCXBPNDYHWECTWWCJMBTXCHXYQQLLXFLYXLLJLSSNWDBZCMYJCLWSWDCZPCHQEKCQBWLCGYDBLQPPQZQFNQDJHYMMCXTXD"
"RMZWRHXCJZYLQXDYYNHYYHRSLNRSYWWJJYMTLTLLGTQCJZYABTCKZCJYCCQLYSQXALMZYNYWLWDNZXQDLLQSHGPJFJLJNJABCQZD"
"JGTHHSSTNYJFBSWZLXJXRHGLDLZRLZQZGSLLLLZLYMXXGDZHGBDPHZPBRLWNJQBPFDWONNNHLYPCNJCCNDMBCPBZZNCYQXLDOMZB"
"LZWPDWYYGDSTTHCSQSCCRSSSYSLFYBNNTYJSZDFNDPDHTQZMBQLXLCMYFFGTJJQWFTMNPJWDNLBZCMMCNGBDZLQLPNFHYYMJYLSD"
"CHDCJWJCCTLJCLDTLJJCBDDPNDSSZYCNDBJLGGJZXSXNLYCYBJJXXCBYLZCFZPPGKCXQDZFZTJJFJDJXZBNZYJQCTYJWHDYCZHYM"
"DJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTACBBMGDEWYCYZXDSZJYHFLYSTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLL"
"MJYYHFLLQLLXFDYHABXGGNYWYYPLLSDLDLLBJCYXJZNLHLJDXYYQYTDLLLBNGPFDFBBQBZZMDPJHGCLGMJJPGAEHHBWCQXAJHHHZ"
"CHXYPHJAXHLPHJPGPZJQCQZGJJZZGZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXJPGALXZDAGLMDGXMMZQWTXDXXPFDMMSSY"
"MPFMDMMKXKSYZYSHDZKJSYSMMZZZMDYDYZZCZXBMLSTMDYEMXCKJMZTYYMZMZZMSSHHDCCJEWXXKLJSTHWLSQLYJZLLSJSSDPPMH"
"NLGJCZYHMXXHGNCJMDHXTKGRMXFWMCKMWKDCKSXQMMMSZZYDKMSCLCMPCJMHRPXQPZDSSLCXKYXTWLKJYAHZJGZJWCJNXYHMMBML"
"GJXMHLMLGMXCTKZMJLYSCJSYSZHSYJZJCDAJZHBSDQJZGWTKQXFKDMSDJLFMNHKZQKJFEYPZYSZCDPYNFFMZQYKTTDZZEFMZLBNP"
"PLPLPBPSZALLTNLKCKQZKGENJLWALKXYDPXNHSXQNWQNKXQCLHYXXMLNCCWLYMQYCKYNNLCJNSZKPYZKCQZQLJBDMDJHLASQLBYD"
"WQLWDGBQCRYDDZTJYBKBWSZDXDTNPJDTCNQNFXQQMGNSECLSTBHPWSLCTXXLPWYDZKLNQGZCQAPLLKQCYLBQMQCZQCNJSLQZDJXL"
"DDHPZQDLJJXZQDJYZHHZLKCJQDWJPPYPQAKJYRMPZBNMCXKLLZLLFQPYLLLMBSGLZYSSLRSYSQTMXYXZQZBSCNYSYZTFFMZZSMZQ"
"HZSSCCMLYXWTPZGXZJGZGSJZGKDDHTQGGZLLBJDZLSBZHYXYZHZFYWXYTYMSDNZZYJGTCMTNXQYXJSCXHSLNNDLRYTZLRYYLXQHT"
"XSRTZCGYXBNQQZFHYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZTJCTZHHYZZJRDYZHNFXKLFZSLKGJTCTSSYLLGZRZBBJZZKLPKBCZYS"
"NNYXBJFBNJZZXCDWLZYJXZZDJJGGGRSNJKMSMZJLSJYWQSNYHQJSXPJZTNLSNSHRNYNJTWCHGLBNRJLZXWJQXQKYSJYCZTLQZYBB"
"YBYZJQDWGYZCYTJCJXCKCWDKKZXSNKDNYWWYYJQYYTLYTDJLXWKCJNKLCCPZCQQDZZQLCSFQCHQQGSSMJZZLLBJJZYSJHTSJDYSJ"
"QJPDSZCDCHJKJZZLPYCGMZNDJXBSJZZSYZYHGXCPBJYDSSXDZNCGLQMBTSFCBFDZDLZNFGFJGFSMPNJQLNBLGQCYYXBQGDJJQSRF"
"KZTJDHCZKLBSDZCFYTPLLJGJHTXZCSSZZXSTJYGKGCKGYNQXJPLZBBBGCGYJZGCZQSZLBJLSJFZGKQQJCGYCJBZQTLDXRJNBSXXP"
"ZSHSZYCFWDSJJHXMFCZPFZHQHQMQNKNLYHTYCGFRZGNQXCGPDLBZCSCZQLLJBLHBDCYPSCPPDYMZZXGYHCKCPZJGSLZLNSCNSLDL"
"XBMSDLDDFJMKDQDHSLZXLSZNPQPGJDLYBDSKGQLBZLNLKYYHZTTMCJNQTZZFSZQKTLLJTYYLLNLLQYZQLBDZLSLYYZXMDFSZSNXL"
"XZNCZQNBBWSKRFBCYLCTNBLGJPMCZZLSTLXSHTZCYZLZBNFMQNLXFLCJLYLJQCBCLZJGNSSTBRMHXZHJZCLXFNBGXGTQNCZTMSFZ"
"KJMSSNCLJKBHSZJNTNLZDNTLMMJXGZJYJCZXYHYHWRWWQNZTNFJSCPYSHZJFYRDJSFSCJZBJFZQZCHZLXFXSBZQLZSGYFTZDCSZX"
"ZJBJPSZKJRHXJZCGBJKHCGGTXKJQGLXBXFGTRTYLXQXHDTSJXHJZJJCMZLCQSBTXWQGXTXXHXFTSDKFJHZYJFJXNZLDLLLCQSQQZ"
"QWQXSWQTWGWBZCGCLLQZBCLMQJTZGZYZXLJFRMYZFLXNSNXXJKXRMJDZDMMYXBSQBHGZMWFWYGMJLZBYYTGZYCCDJYZXSNGNYJYZ"
"NBGPZJCQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJSSFSBYSMZQHXXNXRXHQZZZSSLYFLCZJRCRXHHZXQNDSHXSJJH"
"QCJJBCYNSYSXJBQJPXZQPLMLXZKYXLXCNLCYCXXZZLXDLLLMJYHZXHYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJ"
"KRDHHJXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFCGCLYJBPMLYSMSXLSZJQQHJZFX"
"GFQFQBPHNGYYQXGZTNQWYLTLGWGWWHNLFMFGZJMGMGBGTJFLYZZGZYZAFLSSPMLBFLCWBJZTLJJMZLPJJLYMQTMYYYFBGYGQZGLY"
"ZDXQYXRQQQHSXYYQXYGJTYXFSFSLLGNQCYGYCWFHCCCFXPYLYPLLZQXXXXXQQHHSSHJZCFTSCZJXSPZWHHHHHAPYLQNLPQAFYHXD"
"YLNKMZQGGGDDESRENZLTZGCHYPPCSQJJHCLLJTOLNJPZLJLHYMHEZDYDSQYCDDHGZNNDZCLZYWLLZNTEYDGNLHSLPJJBDGWXPCNN"
"TYCKLKCLWKLLCASSTKNZDNNJTTLYYZSSYSSZZRYLJQKCGDHHYRXRZYDGRGCWCGZQFFBPPJFZYNAKRGYWYJPQXXFKJTSZZXSWZDDF"
"BBQTBGTZKZNPZFPZXZPJSZBMQHKYYXYLDKLJNYPKYGHGDZJXXEAXPNZNCTZCMXCXMMJXNKSZQNMNLWBWWQJJYHCLSTMCSXNJCXXT"
"PCNFDTNNPGLLLZCJLSPBLPGJCDTNJJLYARSCFFJFQWDPGZDWMRZZCGODAXNSSNYZRESTYJWJYJDBCFXNMWTTBQLWSTSZGYBLJPXG"
"LBNCLGPCBJFTMXZLJYLZXCLTPNCLCGXTFZJSHCRXSFYSGDKNTLBYJCYJLLSTGQCBXNHZXBXKLYLHZLQZLNZCQWGZLGZJNCJGCMNZ"
"ZGJDZXTZJXYCYYCXXJYYXJJXSSSJSTSSTDPPGHTCSXWZDCSYNPTFBCHFBBLZJCLZZDBXGCJLHPXNFZFLSYLTNWBMNJHSZBMDNBCY"
"SCCLDNYCNDQLYJJHMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXBFTWWZQSWQRFKJLZJQQYFBRXJHHFWJGZYQAC"
"MYFRHCYYBYNWLPEXCCZSYYRLTTDMQLRKMPBGMYYJPRKZNBBSQYXBHYZDJDNGHPMFSGBWFZMFQMMBZMZDCGJLNNNXYQGMLRYGQCCY"
"XZLWDKCJCGGMCJJFYZZJHYCFRRCMTZNZXHKQGDJXCCJEASCRJTHPLJLRZDJRBCQHJDNRHYLYQJSYMHZYDWCDFRYHBBYDTSSCCWBX"
"GLPZMLZJDQSSCFJMMXJCXJYTYCGHYCJWYNSXLFEMWJNMKLLSWTXHYYYNCMMCYJDQDJZGLLJWJNKHPZGGFLCCSCZMCBLTBHBQJXQD"
"JPDJZTGHGLFJAWBZYZJLTSTDHJHCTCBCHFLQMPWDSHYYTQWCNNTJTLNNMNNDYYYXSQKXWYYFLXXNZWCXYPMAELYHGJWZZJBRXXAQ"
"JFLLPFHHHYTZZXSGQJMHSPGDZQWBWPJHZJDYJCQWXKTHXSQLZYYMYSDZGNQCKKNJLWPNSYSCSYZLNMHQSYLJXBCXTLHZQZPCYCYK"
"PPPNSXFYZJJRCEMHSZMNXLXGLRWGCSTLRSXBYGBZGNXCNLNJLCLYNYMDXWTZPALCXPQJCJWTCYYJLBLXBZLQMYLJBGHDSLSSDMXM"
"BDCZSXYHAMLCZCPJMCNHJYJNSYKCHSKQMCZQDLLKABLWJQSFMOCDXJRRLYQCHJMYBYQLRHETFJZFRFKSRYXFJDWTSXXYWSQJYSLY"
"XWJHSDLXYYXHBHAWHWJCXLMYLJCSQLKYDTTXBZSLFDXGXSJKHSXXYBSSXDPWNCMRPTQZCZENYGCXQFJXKJBDMLJZMQQXNOXSLYXX"
"LYLLJDZPTYMHBFSTTQQWLHSGYNLZZALZXCLHTWRRQHLSTMYPYXJJXMNSJNNBRYXYJLLYQYLTWYLQYFMLKLJDNLLTFZWKZHLJMLHL"
"JNLJNNLQXYLMBHHLNLZXQCHXCFXXLHYHJJGBYZZKBXSCQDJQDSNDZSYGZHHMGSXCSYMXFEPCQWWRBPYYJQRYQCYJHQQZYHMWFFHG"
"ZFRJFCDBXNTQYZPCYHHJLFRZGPBXZDBBGRQSTLGDGYLCQMGCHHMFYWLZYXKJLYPJHSYWMQQGGZMNZJNSQXLQSYJTCBEHSXFSZFXZ"
"WFLLBCYYJDYTDTHWZSFJMQQYJLMQSXLLDTTKGHYBFPWDYYSQQRNQWLGWDEBZWCYYGCNLKJXTMXMYJSXHYBRWFYMWFRXYYMXYSCTZ"
"ZTFYKMLDHQDLGYJNLCRYJTLPSXXXYWLSBRRJWXHQYBHTYDNHHXMMYWYTYCNNMNSSCCDALWZTCPQPYJLLQZYJSWJWZZMMGLMXCLMX"
"NZMXMZSQTZPPJQBLPGXJZHFLJJHYCJSRXWCXSNCDLXSYJDCQZXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLFYPRGJY"
"NXCQQDCMQJZZXHNPNXZMEMMSXYKYNLXSXTLJXYHWDCWDZHQYYBGYBCYSCFGFSJNZDRZZXQXRZRQJJYMCANHRJTLDBPYZBSTJHXXZ"
"YPBDWFGZZRPYMNNKXCQBYXNBNFYCKRJJCMJEGRZGYCLNNZDNKKNSJKCLJSPGYYCLQQJYBZSSQLLLKJFTBGTYLCCCDBLSPPFYLGYD"
"TZJQJZGKNTSFCXBDKDXXHYBBFYTYHBCLNNYTGDHRYRNJSBTCSNYJQHKLLLZSLYDXXWBCJQSBXNPJZJZJDZFBXXBRMLADHCSNCLBJ"
"DSTBLPRZNSWSBXBCLLXXLZDNZSJPYNYXXYFTNNFBHJJJGBYGJPMMMMSSZLJMTLYZJXSWXTYLEDQPJMPGQZJGDJLQJWJQLLSDGJGY"
"GMSCLJJXDTYGJQJJJCJZCJGDZDSHQGZJGGCJHQXSNJLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYXJXNCY"
"ZXFXCSXSZXYYSCHSHXZZZGZZZGFJDLDYLNPZGSJAZTYQZPBXCBDZTZCZYXXYHHSCJSHCGGQHJHGXHSCTMZMEHYXGEBTCLZKKWYTJ"
"ZRSLEKESTDBCYHQQSAYXCJXWWGSPHJSZSDNCSJKQCXSWXFCTYNYDPCCCZJQTCWJQJZZZQZLJZHLSBHPYDXPSXSHHEZDXFPTJQYZC"
"XHYAXNCFZYYHXGNQMYWNTZSJBNHHGYMXMXQCNSSBCQSJYXXTYYHYBCQLMMSZMJZZLLCOGXZAAJZYHJMCHHCXZSXSDZNLEYJJZJBH"
"ZWJZSQTZPSXZZDSQJJJLNYAZPHHYYSRNQZTHZHNYJYJHDZXZLSWCLYBZYECWCYCRYLCHZHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYN"
"XELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSDCLZSTSYMCDHJXXYWEYXCZAYD"
"MPXMDSXYBSQMJMZJMTJQLPJYQZCGQHYJHHHQXHLHDLDJQCFDWBSXFZZYYSCHTYTYJBHECXHJKGQFXBHYZJFXHWHBDZFYZBCHPNPG"
"DYDMSXHKHHMAMLNBYJTMPXEJMCTHQBZYFCGTYHWPHFTGZZEZSBZEGPBMDSKFTYCMHBLLHGPZJXZJGZJYXZSBBQSCZZLZSCSTPGXM"
"JSFDCCZJZDJXSYBZLFCJSAZFGSZLWBCZZZBYZTZYNSWYJGXZBDSYNXLGZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQ"
"ZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQQXCJQCCCCDJCDSZZYQJCCGXZTDLGSCXZSYJJQTCCLQDQZTQCHQ"
"QYZYNZZZPBKHDJFCJFZTYPQYQTTYNLMBDKTJCPQZJDZFPJSBNJLGYJDXJDCQKZGQKXCLBZJTCJDQBXDJJJSTCXNXBXQMSLYJCXNT"
"JQWWCJJNJJLLLHJCWQTBZQQCZCZPZZDZYDDCYZDZCCJGTJFZDPRNTCTJDCXTQZDTJNPLZBCLLCTDSXKJZQDMZLBZNBTJDCXFCZDB"
"CZJJLTQQPLDCKZTBBZJCQDCJWYNLLZLZCCDWLLXWZLXRXNTQJCZXKJLSGDNQTDDGLNLAJJTNNYNKQLLDZNTDNYCYGJWYXDXFRSQS"
"TCDENQMRRQZHHQHDLDAZFKAPBGGPZREBZZYKYQSPEQJJGLKQZZZJLYSYHYZWFQZNLZZLZHWCGKYPQGNPGBLPLRRJYXCCCGYHSFZF"
"WBZYWTGZXYLJCZWHNCJZPLFFLGSKHYJDEYXHLPLLLLCYGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJWSPYXZLZLXGCCP"
"ZBLLCXBBBBNBBCBBCRNNZCCNRBBNNLDCGQYYQXYGMQZWNZYTYJHYFWTEHZNJYWLCCNTZYJJCDEDPWDZTSTNJHTYMBJNYJZLXTSST"
"PHNDJXXBYXQTZQDDTJTDYZTGWSCSZQFLSHLNZBCJBHDLYZJYCKWTYDYLBNYDSDSYCCTYSZYYEBGEXHQDDWNYGYCLXTDCYSTQNYGZ"
"ASCSSZZDZLCCLZRQXYYWLJSBYMXSHZDEMBBLLYYLLYTDQYSHYMRQNKFKBFXNNSBYCHXBWJYHTQBPBSBWDZYLKGZSKYGHQZJXHXJX"
"GNLJKZLYYCDXLFWFGHLJGJYBXBLYBXQPQGNTZPLNCYBXDJYQYDYMRBEYJYYHKXXSTMXRCZZJWXYHYBMCFLYZHQYZFWXDBXBCWZMS"
"LPDMYCKFMZKLZCYQYCCLHXFZLYDQZPZYGYJYZMDXTZFNNYTTQTZHGSFCDMLCCYTZXJCYTJMKSLPZHYSNWLLYTPZCTZCCKTXDHXXT"
"QCYFKSMQCCYYAZHTJPLYLZLYJBJXTFNYLJYYNRXCYLMMNXJSMYBCSYSSLZYLLJJGYLDZDLQHFZZBLFNDSQKCZFYHHGQMJDSXYCTT"
"XNQNJPYYBFCJTYYFBNXEJDGYQBJRCNFYYQPGHYJSYZNGRHTKNLNNDZNTSMGKLBYGBPYSZBYDJZSSTJZTSXZBHBSCSBZCZPTQFZLQ"
"FLYPYBBJGSZMNXDJMTSYSKKBJTXHJCEGBSMJYJZCSTMLJYXRCZQSCXXQPYZHMKYXXXJCLJYRMYYGADYSKQLNADHRSKQXZXZTCGGZ"
"DLMLWXYBWSYCTBHJHCFCWZSXWWTGZLXQSHNYCZJXEMPLSRCGLTNZNTLZJCYJGDTCLGLBLLQPJMZPAPXYZLAKTKDWCZZBNCCTDQQZ"
"QYJGMCDXLTGCSZLMLHBGLKZNNWZNDXNHLNMKYDLGXDTWCFRJERCTZHYDXYKXHWFZCQSHKNMQQHZHHYMJDJSKHXZJZBZZXYMPAJNM"
"CTBXLSXLZYNWRTSQGSCBPTBSGZWYHTLKSSSWHZZLYYTNXJGMJRNSNNNNLSKZTXGXLSAMMLBWLDQHYLAKQCQCTMYCFJBSLXCLZJCL"
"XXKNBNNZLHJPHQPLSXSCKSLNHPSFQCYTXJJZLJLDTZJJZDLYDJNTPTNNDSKJFSLJHYLZQQZLBTHYDGDJFDBYADXDZHZJNTHQBYKN"
"XJJQCZMLLJZKSPLDSCLBBLNNLELXJLBJYCXJXGCNLCQPLZLZNJTSLJGYZDZPLTQCSSFDMNYCXGBTJDCZNBGBQYQJWGKFHTNBYQZQ"
"GBKPBBYZMTJDYTBLSQMBSXTBNPDXKLEMYYCJYNZDTLDYKZZXTDXHQSHYGMZSJYCCTAYRZLPWLTLKXSLZCGGEXCLFXLKJRTLQJAQZ"
"NCMBQDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLHBYJBRBTMLBYJDZXLCJLPLDLPCQDHLHZLYCBLCXCCJAD"
"QLMZMMSSHMYBHBNKKBHRSXXJMXMDZNNPKLBBRHGGHFCHGMNKLLTSYYYCQLCSKYMYEHYWXNXQYWBAWYKQLDNNTNDKHQCGDQKTGPKX"
"HCPDHTWNMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLDYYCXWHYYCLQHKQHTDQKHFFLDXQWYTYYDESBPKYRZPJFYYZJCEQDZZDLATTPB"
"FJLLCXDLMJSDXEGWGSJQXCFBSSSZPDYZCXZNYXPPZYDLYJCCPLTXLNXYZYRSCYYYTYLWWNDSAHJSYGYHGYWWAXTJZDAXYSRLTDPS"
"SYXFNEJDXYZHLXLLLZHZSJNYQYQYXYJGHZGJCYJCHZLYCDSHHSGCZYJSCLLNXZJJYYXNFSMWFPYLLYLLABMDDHWZXJMCXZTZPMLQ"
"CHSFWZYNCTLNDYWLSLXHYMMYLMBWWKYXYADDXYLLDJPYBPWNXJMMMLLHAFDLLAFLBNHHBQQJQZJCQJJDJTFFKMMMPYTHYGDRJRDD"
"WRQJXNBYSRMZDBYYTBJHPYMYJTJXAAHGGDQTMYSTQXKBTZBKJLXRBYQQHXMJJBDJNTGTBXPGBKTLGQXJJJCDHXQDWJLWRFMJGWQH"
"CNRXSWGBTGYGBWHSWDWRFHWYTJJXXXJYZYSLPHYYPYYXHYDQPXSHXYXGSKQHYWBDDDPPLCJLHQEEWJGSYYKDPPLFJTHKJLTCYJHH"
"JTTPLTZZCDLYHQKCJQYSTEEYHKYZYXXYYSDDJKLLPYMQYHQGXQHZRHBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPHTHYYKTYEZ"
"YENMDSHLZRPQFBNFXZBSFTLGXSJBSWYYSKSFLXLPPLBBBLNSFBFYZBSJSSYLPBBFFFFSSCJDSTJSXTRYJCYFFSYZYZBJTLCTSBSD"
"HRTJJBYTCXYYEYLYCBNEBJDSYSYHGSJZBXBYTFZWGENHHHTHJHHXFWGCSTBGXKLSTYYMTMBYXJSKZSCDYJRCYTHXZFHMYMCXLZNS"
"DJTXTXRYCFYJSBSDYERXHLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBBTHFJYAFXWXFBXMYFHDTTCXZZPXRSYWZDLYBBKTYQW"
"QJBZYPZJZNJPZJLZTFYSBTTSLMPTZRTDXQSJEHBNYLNDXLJSQMLHTXTJECXALZZSPKTLZKQQYFSYJYWPCPQFHJHYTQXZKRSGTKSQ"
"CZLPTXCDYYZSSLZSLXLZMACPCQBZYXHBSXLZDLTZTJTYLZJYYTBZYPLTXJSJXHLBMYTXCQRBLZSSFJZZTNJYTXMYJHLHPBLCYXQJ"
"QQKZZSCPZKSWALQSPLCZZJSXGWWWYGYATJBBCTDKHQHKGTGPBKQYSLBXBBCKBMLLNDZSTBKLGGQKQLZBKKTFXRMDKBFTPZFRTPPM"
"FERQNXGJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNHXDKDDJCYYLJFQGZLGSYGMJQJKHBPMXYXLYTQWLWJCPBMJXC"
"YZYDRJBHTDJYEQSHTMGSFYPLWHLZFFNYNNHXQHPLTBQPFBJWJDBYGPNXTBFZJGNNNTJSHXEAWTZYLLTYQBWJPGXGHNNKNDJTMSZS"
"QYNZGGNWQTFHCLSSGMNNNNYNZQQXNCJDQGZDLFNYKLJCJLLZLMZZNNNNSSHTHXJLZJBBHQJWWYCRDHLYQQJBEYFSJHTHNRNWJHWP"
"SLMSSGZTTYGRQQWRNLALHMJTQJSMXQBJJZJQZYZKXBJQXBJXSHZSSFGLXMXNXFGHKZSZGGSLCNNARJXHNLLLMZXELGLXYDJYTLFB"
"KBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPJLBXBMMYWXGSLZHGLSGNYF"
"LJBYFDJFNGSFMBYZHQFFWJSYFYJJPHZBYYZFFWOTJNLMFTWLBZGYZQXCDJYGZYYRYZYNYZWEGAZYHJJLZRTHLRMGRJXZCLNNNLJJ"
"YHTBWJYBXXBXJJTJTEEKHWSLNNLBSFAZPQQBDLQJJTYYQLYZKDKSQJNEJZLDQCGJQNNJSNCMRFQTHTEJMFCTYHYPYMHYDMJNCFGY"
"YXWSHCTXRLJGJZHZCYYYJLTKTTNTMJLZCLZZAYYOCZLRLBSZYWJYTSJYHBYSHFJLYKJXXTMZYYLTXXYPSLQYJZYZYYPNHMYMDYYL"
"BLHLSYYGQLLNJJYMSOYCBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJL"
"JXCJJYCLYCJBCPZJZJMMWLCJLNQLJJJLXYJMLSZLJQLYCMMGCFMMFPQQMFXLQMCFFQMMMMHNZNFHHJGTTHXKHSLNCHHYQZXTMMQD"
"CYDYXYQMYQYLDDCYAYTAZDCYMDYDLZFFFMMYCQCWZZMABTBYCTDMNDZGGDFTYPCGQYTTSSFFWBDTTQSSYSTWNJHJYTSXXYLBYYHH"
"WHXGZXWZNNQZJZJJQJCCCHYKXBZSZCNJTLLCQXYNJNCKYCYNCCQNXYEWYCZDCJYCCHYJLBTZYYCQWLPGPYLLGKTLTLGKGQBGYCHJ"
"XY";

@implementation NSArray (Additions)
- (NSString*)JSONString {
    NSData* data = [NSJSONSerialization dataWithJSONObject:self options:NSJSONWritingPrettyPrinted error:nil];
    NSString* json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    return json;
}
@end
@implementation NSMutableArray(Additions)
- (id)deleteAtIndex:(NSInteger)index {
    if (self.count <= 0) {
        return nil;
    }
    
    if (index >= 0) {
        if (index >= self.count) {
            return nil;
        }
        else {
            id obj = self[index];
            [self removeObjectAtIndex:index];
            return obj;
        }
    }
    else {
        index = -index;
        if (index > self.count) {
            return nil;
        }
        else {
            id obj = self[self.count-index];
            [self removeObjectAtIndex:self.count-index];
            return obj;
        }
    }
}
@end

@implementation NSDictionary (Additions)
- (NSString*)JSONString {
    NSData* data = [NSJSONSerialization dataWithJSONObject:self options:NSJSONWritingPrettyPrinted error:nil];
    NSString* json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    return json;
}
- (NSString*)stringForKey:(NSString*)key placeholder:(NSString*)placeholder {
    NSString* value = self[key];
    if (value.length <= 0) {
        return placeholder;
    }
    return value;
}
@end

@implementation NSString (Additions)

- (BOOL)isEmail {
    NSPredicate* predicate = [NSPredicate predicateWithFormat:@"SELF MATCHES %@", @"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"];
    return [predicate evaluateWithObject:self];
}
- (BOOL)isAppURL {
    return [self hasPrefix:@"itms-services://"];
}
- (BOOL)isBusLine {
    return [self hasPrefix:@"tbsport://"];
}
- (BOOL)isWebURL {
    return [self hasPrefix:@"http"];
}
- (BOOL)isFileExist {
    return [NSFileManager.defaultManager fileExistsAtPath:self];
}
- (BOOL)isFileNotExist {
    return ![NSFileManager.defaultManager fileExistsAtPath:self];
}

- (void)mkdir {
    if (self.isFileNotExist) {
        [NSFileManager.defaultManager createDirectoryAtPath:self withIntermediateDirectories:YES attributes:nil error:nil];
    }
}
- (void)removePathfile {
    [NSFileManager.defaultManager removeItemAtPath:self error:nil];
}
- (void)renameFile:(NSString*)name {
    NSString* pathfile = [[self stringByDeletingLastPathComponent] stringByAppendingPathComponent:name];
    [NSFileManager.defaultManager moveItemAtPath:self toPath:pathfile error:nil];
}
- (void)renamePathfile:(NSString*)pathfile {
    [NSFileManager.defaultManager moveItemAtPath:self toPath:pathfile error:nil];
}

- (NSURL*)URL {
    if ([self hasPrefix:@"http"]) {
        return [NSURL URLWithString:self];
    }
    else if ([self hasPrefix:@"//"]) {
        return [NSURL URLWithString:[@"http:" stringByAppendingString:self]];
    }
    else {
        return [NSURL fileURLWithPath:self];
    }
}
- (NSURLRequest*)request {
    return [NSURLRequest requestWithURL:self.URL];
}

- (UInt64)timeWithFormat:(NSString*)format {
    NSDate* date = [self dateWithFormat:format];
    UInt64 time = [date timeIntervalSince1970];
    return time * 1000;
}
- (NSDate*)dateWithFormat:(NSString*)format {
    if (self.length <= 0) {
        return nil;
    }
    NSDateFormatter* formater = [[NSDateFormatter alloc] init];
    formater.dateFormat = format;
    return [formater dateFromString:self];
}

- (NSString*)md5 {
    if ([self length] <= 0) {
        return nil;
    }
    const char* cString = [self UTF8String];
    unsigned char result[32];
    CC_MD5(cString, (CC_LONG)strlen(cString), result);
    return [NSString stringWithFormat:@"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x", result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7], result[8], result[9], result[10], result[11], result[12], result[13], result[14], result[15]];
}
- (NSString*)MD5 {
    if ([self length] <= 0) {
        return nil;
    }
    const char* cString = [self UTF8String];
    unsigned char result[32];
    CC_MD5(cString, (CC_LONG)strlen(cString), result);
    return [NSString stringWithFormat:@"%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X", result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7], result[8], result[9], result[10], result[11], result[12], result[13], result[14], result[15]];
}

- (NSString*)sha1 {
    NSData* data = [self dataUsingEncoding:NSUTF8StringEncoding];
    uint8_t digest[CC_SHA1_DIGEST_LENGTH];
    CC_SHA1(data.bytes, (uint32_t)data.length, digest);
    
    NSMutableString* code = [NSMutableString stringWithCapacity:CC_SHA1_DIGEST_LENGTH * 2];
    for(NSInteger i = 0; i < CC_SHA1_DIGEST_LENGTH; i++) {
        [code appendFormat:@"%02x", digest[i]];
    }
    return code;
}
- (NSString*)SHA1 {
    NSData* data = [self dataUsingEncoding:NSUTF8StringEncoding];
    uint8_t digest[CC_SHA1_DIGEST_LENGTH];
    CC_SHA1(data.bytes, (uint32_t)data.length, digest);
    
    NSMutableString* code = [NSMutableString stringWithCapacity:CC_SHA1_DIGEST_LENGTH * 2];
    for(NSInteger i = 0; i < CC_SHA1_DIGEST_LENGTH; i++) {
        [code appendFormat:@"%02X", digest[i]];
    }
    return code;
}

- (NSString*)hmacsha1:(NSString*)key {
    NSData* dkey = [key dataUsingEncoding:NSUTF8StringEncoding];
    NSData* dthis = [self dataUsingEncoding:NSUTF8StringEncoding];
    uint8_t digest[CC_SHA1_DIGEST_LENGTH];
    CCHmac(kCCHmacAlgSHA1, dkey.bytes, dkey.length, dthis.bytes, dthis.length, digest);
    
    NSMutableString* code = [NSMutableString stringWithCapacity:CC_SHA1_DIGEST_LENGTH * 2];
    for(NSInteger i = 0; i < CC_SHA1_DIGEST_LENGTH; i++) {
        [code appendFormat:@"%02x", digest[i]];
    }
    return code;
}
- (NSString*)HMACSHA1:(NSString*)key {
    NSData* dkey = [key dataUsingEncoding:NSUTF8StringEncoding];
    NSData* dthis = [self dataUsingEncoding:NSUTF8StringEncoding];
    uint8_t digest[CC_SHA1_DIGEST_LENGTH];
    CCHmac(kCCHmacAlgSHA1, dkey.bytes, dkey.length, dthis.bytes, dthis.length, digest);
    
    NSMutableString* code = [NSMutableString stringWithCapacity:CC_SHA1_DIGEST_LENGTH * 2];
    for(NSInteger i = 0; i < CC_SHA1_DIGEST_LENGTH; i++) {
        [code appendFormat:@"%02X", digest[i]];
    }
    return code;
}

- (NSString*)trim {
    return [self stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
}

- (NSString*)fileMD5 {
    return self.isFileExist ? [[NSData dataWithContentsOfURL:[NSURL fileURLWithPath:self]] md5] : nil;
}

- (NSString*)encodeURL {
    if ([self length] <= 0) {
        return @"";
    }
    CFStringRef pattern = (CFStringRef)@"!*'();:@&=+$,/?%#[]";
    return (NSString*)CFBridgingRelease(CFURLCreateStringByAddingPercentEscapes(kCFAllocatorDefault, (CFStringRef)self, NULL, pattern, kCFStringEncodingUTF8));
}
- (NSString*)decodeURL {
    if ([self length] <= 0) {
        return @"";
    }
    
    NSMutableString* result = [NSMutableString stringWithString:self];
    [result replaceOccurrencesOfString:@"+" withString:@" " options:NSLiteralSearch range:NSMakeRange(0, [result length])];
    return [result stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
}

- (NSString*)imageURLWithExt:(CGFloat)size {
    size = size * [UIScreen mainScreen].scale;
    NSString* ext = nil;
    if (size <= 80) {
        ext = @"_80x80.jpg";
    } else if (size <= 160) {
        ext = @"_160x160.jpg";
    } else if (size <= 240) {
        ext = @"_240x240.jpg";
    } else if (size <= 320) {
        ext = @"_320x320.jpg";
    } else if (size <= 400) {
        ext = @"_400x400.jpg";
    } else if (size <= 480) {
        ext = @"_480x480.jpg";
    } else if (size <= 560) {
        ext = @"_560x560.jpg";
    } else if (size <= 640) {
        ext = @"_640x640.jpg";
    } else if (size <= 750) {
        ext = @"_720x720.jpg";
    } else if (size <= 1080) {
        ext = @"_960x960.jpg";
    }
    return ext ? [self stringByAppendingString:ext] : self;
}

- (NSString*)bundlePath {
    return [[NSBundle mainBundle] pathForResource:self ofType:nil];
}

- (NSString*)uniqueName {
    NSString* ext = self.stringByRomoveQuery.pathExtension.lowercaseString;
    if (ext.length <= 0) {
        return @(self.hash).stringValue;
    }
    
    NSMutableString* name = [NSMutableString stringWithCapacity:48];
    [name appendString:@(self.hash).stringValue];
    [name appendString:@"."];
    [name appendString:ext];
    return name;
}

- (NSString*)httpResponse {
    return  [NSString stringWithContentsOfURL:self.URL usedEncoding:nil error:nil];
}

- (NSString*)firstUppercase {
    return [self stringByReplacingCharactersInRange:NSMakeRange(0, 1) withString:[self substringToIndex:1].capitalizedString];
}
- (NSString*)firstPinyinLetter {
    NSString* words = [self trim];
    unichar word = [(words.length <= 0 ? @"#" : words) characterAtIndex:0];
    NSInteger index = word - HANZI_START;
    if (index >= 0 && index < HANZI_COUNT) {
        return [[NSString stringWithFormat:@"%c", FirstLetterArray[index]] uppercaseString];
    }
    else if ((word >= 'a' && word <= 'z') || (word >= 'A' && word <= 'Z')) {
        return[[NSString stringWithFormat:@"%c", word] uppercaseString];
    }
    else {
        return @"#";
    }
}

- (NSString*)stringByRemoveHash {
    NSRange hash = [self rangeOfString:@"#"];
    return hash.location == NSNotFound ? self : [self substringToIndex:hash.location];
}
- (NSString*)stringByRomoveQuery {
    NSRange query = [self rangeOfString:@"?"];
    return query.location == NSNotFound ? self : [self substringToIndex:query.location];
}
- (NSString*)stringByAppendParameter:(NSString*)parameter {
    if ([self rangeOfString:@"?"].location == NSNotFound) {
        return [self stringByAppendingFormat:@"?%@", parameter];
    }
    else {
        return [self stringByAppendingFormat:@"&%@", parameter];
    }
}
+ (NSString*)stringWithTime:(NSUInteger)time format:(NSString*)format {
    NSDate* date = [NSDate dateWithTimeIntervalSince1970:time];
    return [date stringWithFormat:format];
}

- (const char*)GBKString {
    return [self cStringUsingEncoding:CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000)];
}

- (NSMutableDictionary*)dictionaryForURL {
    NSMutableDictionary* params = [NSMutableDictionary dictionary];
    if ([self length] <= 0) {
        return params;
    }
    NSArray* keyvalues = [self componentsSeparatedByString:@"&"];
    [keyvalues enumerateObjectsUsingBlock:^(NSString* keyvalue, NSUInteger idx, BOOL *stop) {
        keyvalue = [keyvalue trim];
        if (keyvalue.length <= 0) {
            return;
        }
        NSRange range = [keyvalue rangeOfString:@"="];
        if (range.location == NSNotFound) {
            params[keyvalue] = @"";
        }
        else {
            NSString* key = [keyvalue substringToIndex:range.location];
            NSString* value = [keyvalue substringFromIndex:range.location + 1].decodeURL;
            params[key] = value;
        }
    }];
    return params;
}

- (id)objectFromJSONString {
    return [[self dataUsingEncoding:NSUTF8StringEncoding] objectFromJSONString];
}

- (NSTextContainer*)containerWithFont:(UIFont*)font size:(CGSize)size color:(NSInteger)color line:(CGFloat)line paragraph:(CGFloat)paragraph indent:(CGFloat)indent {
    NSTextContainer* container = [[NSTextContainer alloc] initWithSize:size];
    NSTextStorage* storage = [[NSTextStorage alloc] initWithString:self];
    [storage addAttribute:NSFontAttributeName value:font range:NSMakeRange(0, self.length)];
    [storage addAttribute:NSForegroundColorAttributeName value:[UIColor RGBAColor:color] range:NSMakeRange(0, self.length)];
    [storage addAttribute:NSParagraphStyleAttributeName value:({
        NSMutableParagraphStyle* style = [[NSMutableParagraphStyle alloc] init];
        style.alignment           = NSTextAlignmentLeft;  // 对齐方式
        style.headIndent          = 0.0f;                 // 段落除了第一行的其他文字离边缘间距
        style.tailIndent          = 0.0f;                 // ???????
        style.lineSpacing         = line;                 // 行间距
        style.paragraphSpacing    = paragraph;            // 段间距
        style.minimumLineHeight   = font.pointSize;       // 最小行高
        style.maximumLineHeight   = font.pointSize * 2;   // 最大行高
        style.lineHeightMultiple  = 1.0f;                 // 可变行高,乘因数
        style.firstLineHeadIndent = indent;               // 段落首文字离边缘间距
        style;
    }) range:NSMakeRange(0, self.length)];
    [storage addLayoutManager:({
        NSLayoutManager* layout = [[NSLayoutManager alloc] init];
        [layout addTextContainer:container];
        layout;
    })];
    return container;
}


- (CGSize)textSizeWithFont:(UIFont *)font constrainedToSize:(CGSize)size{
    CGSize textSize;
    if (CGSizeEqualToSize(size, CGSizeZero)){
        NSDictionary *attributes = @{NSFontAttributeName:font};
        textSize = [self sizeWithAttributes:attributes];
    } else {
        NSStringDrawingOptions option = NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading;
        NSDictionary *attributes = [NSDictionary dictionaryWithObject:font forKey:NSFontAttributeName];
        CGRect rect = [self boundingRectWithSize:size options:option attributes:attributes context:nil];
        textSize = rect.size;
    }
    return textSize;
}

@end
